### ISSUE TITLE
Block mode images don't render on light backgrounds on Chrome/macOS

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/media#9]
Screenshots:

<img width="612" alt="Screen Shot 2022-03-26 at 4 15 06 PM" src="https://user-images.githubusercontent.com/797/160258770-c1a39c29-0cfd-459d-8acf-1763522c337b.png">

<img width="633" alt="Screen Shot 2022-03-26 at 4 14 59 PM" src="https://user-images.githubusercontent.com/797/160258771-c935fd4a-02d7-420e-8078-506a9832120b.png">

**Comment by newpavlov** [comment]
Are you using Chrome in dark mode? Can you switch rustdoc CSS to the dark theme and see whether it will help?

**Comment by tarcieri** [comment]
The system theme is dark mode yes.

It looks ok if docs.rs is set to a dark mode:

<img width="1000" alt="Screen Shot 2022-03-26 at 4 25 33 PM" src="https://user-images.githubusercontent.com/797/160258984-5b44d08d-1046-4b59-8a98-cc3a474bd373.png">

...but the problem is the system theme isn't actually helpful if it doesn't match the page background.

Maybe we should just add solid color backgrounds to the images.

FWIW, Safari seems to work OK using the background color of the page to sense which one to use.

**Comment by newpavlov** [comment]
>the system theme isn't actually helpful if it doesn't match the page background.

The issue here is that rustdoc/docs.rs does not set the "Use system theme" flag by default (see settings behind the cog icon). Also AFAIK browsers do not provide any way to overwrite `prefers-color-scheme` selector for a page or domain, so the doc pages can not change it to match a user-chosen theme.

>Maybe we should just add solid color backgrounds to the images.

I thought about it, but they result in annoyingly bright huge rectangles on dark mode and do not look great on grey backgrounds.

Unfortunately, the state of dark-them support in browsers is far from ideal, so we do not have good solutions, only subpar ones.
